# This file is auto-generated by hatch-gradle-version. Do not edit.

GRADLE_VERSION = "1.0.0"
FULL_VERSION = "1.0.0.1.0"

JETBRAINS_ANNOTATIONS_VERSION = "23.0.0"
KOTLIN_STDLIB_DEFAULT_DEPENDENCY = "false"
MAVEN_GROUP = "com.example.hextemplate"
MOD_ID = "hextemplate"
MOD_VERSION = "1.0.0"
ORG_GRADLE_JVMARGS = "-Xmx6096M"
