name: Deploy Site

on:
  workflow_dispatch:
  push:
    branches:
    - copier

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
      
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Build template
      run: nix-build

    - name: Deploy
      run: |
          git config user.name deploy-example
          
          git fetch origin example
          git checkout -B example origin/example

          # remove all but .git and result folder
          find . -mindepth 1 -maxdepth 1 \
            ! -name .git \
            ! -name result \
            -exec rm -rf {} +

          cp -r result/default/. .
          rm result
          mv .github .github-example

          git add -A
          git commit -m "Deploy ${GITHUB_SHA}" || exit 0
          git push origin example